/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSubmissionsIndexRouteImport } from './routes/_auth/submissions/index'
import { Route as AuthEpisodesIndexRouteImport } from './routes/_auth/episodes/index'
import { Route as AuthSubmissionsNewRouteImport } from './routes/_auth/submissions/new'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSubmissionsIndexRoute = AuthSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEpisodesIndexRoute = AuthEpisodesIndexRouteImport.update({
  id: '/episodes/',
  path: '/episodes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSubmissionsNewRoute = AuthSubmissionsNewRouteImport.update({
  id: '/submissions/new',
  path: '/submissions/new',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/submissions/new': typeof AuthSubmissionsNewRoute
  '/episodes': typeof AuthEpisodesIndexRoute
  '/submissions': typeof AuthSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/submissions/new': typeof AuthSubmissionsNewRoute
  '/episodes': typeof AuthEpisodesIndexRoute
  '/submissions': typeof AuthSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/submissions/new': typeof AuthSubmissionsNewRoute
  '/_auth/episodes/': typeof AuthEpisodesIndexRoute
  '/_auth/submissions/': typeof AuthSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/submissions/new' | '/episodes' | '/submissions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/submissions/new' | '/episodes' | '/submissions'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/'
    | '/_auth/submissions/new'
    | '/_auth/episodes/'
    | '/_auth/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/submissions/': {
      id: '/_auth/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthSubmissionsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/episodes/': {
      id: '/_auth/episodes/'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof AuthEpisodesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/submissions/new': {
      id: '/_auth/submissions/new'
      path: '/submissions/new'
      fullPath: '/submissions/new'
      preLoaderRoute: typeof AuthSubmissionsNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSubmissionsNewRoute: typeof AuthSubmissionsNewRoute
  AuthEpisodesIndexRoute: typeof AuthEpisodesIndexRoute
  AuthSubmissionsIndexRoute: typeof AuthSubmissionsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthSubmissionsNewRoute: AuthSubmissionsNewRoute,
  AuthEpisodesIndexRoute: AuthEpisodesIndexRoute,
  AuthSubmissionsIndexRoute: AuthSubmissionsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
