# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: newscast
metadata:
  template: azd-init@1.17.0
workflows:
  up:
    steps:
      - azd: provision
      - azd: deploy --all
services:
  content-api:
    project: ./content-api
    language: java
    host: containerapp
    docker:
      path: ./src/main/docker/Dockerfile.jvm
      image: newscast/content-api
    hooks:
      prebuild:
        windows:
          shell: pwsh
          run: './mvnw "-DskipTests" "-Dquarkus.container-image.build=true" clean package'
        posix:
          shell: sh
          run: './mvnw -DskipTests -Dquarkus.container-image.build=true clean package'
  reader-api:
    project: ./reader-api
    language: java
    host: containerapp
    docker:
      path: ./src/main/docker/Dockerfile.jvm
      image: newscast/reader-api
    hooks:
      prebuild:
        windows:
          shell: pwsh
          run: './mvnw "-DskipTests" "-Dquarkus.container-image.build=true" clean package'
        posix:
          shell: sh
          run: './mvnw -DskipTests -Dquarkus.container-image.build=true clean package'
  podcast-api:
    project: ./podcast-api
    language: java
    host: containerapp
    docker:
      path: ./src/main/docker/Dockerfile.jvm
      image: newscast/podcast-api
    hooks:
      prebuild:
        windows:
          shell: pwsh
          run: './mvnw "-DskipTests" "-Dquarkus.container-image.build=true" clean package'
        posix:
          shell: sh
          run: './mvnw -DskipTests -Dquarkus.container-image.build=true clean package'

    