POST http://localhost:3000/submissions
Content-Type: application/json
Accept: application/json

{
    "url": "https://medium.com/realworld-ai-use-cases/cursor-ai-tip-my-folder-system-trick-that-cut-my-requests-down-by-50-7585c8c248dd",
    "instructions": null
}