name: Continuous integration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'content-api/**'
      - 'podcast-api/**'
      - 'reader-api/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'content-api/**'
      - 'podcast-api/**'
      - 'reader-api/**'
      - '.github/workflows/ci.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run Maven build
      run: ./mvnw clean verify -Dquarkus.test.profile=test
      env:
        TESTCONTAINERS_RYUK_DISABLED: true
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: content-api/target/jacoco-report/jacoco.xml,podcast-api/target/jacoco-report/jacoco.xml,reader-api/target/jacoco-report/jacoco.xml
        flags: content-api
        name: content-api-coverage
        fail_ci_if_error: false
