name: Continuous integration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'content-api/**'
      - 'podcast-api/**'
      - 'reader-api/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'content-api/**'
      - 'podcast-api/**'
      - 'reader-api/**'
      - '.github/workflows/ci.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Install Quarkus CLI
      run: |
        curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
        echo "$HOME/.jbang/bin" >> $GITHUB_PATH
        
    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1

    - name: Run Maven build
      run: |
        export GIT_HASH=$(git rev-parse --short HEAD)
        ./mvnw clean verify -Dquarkus.test.profile=test -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
      env:
        TESTCONTAINERS_RYUK_DISABLED: true
        QUARKUS_LANGCHAIN4J_AZURE_OPENAI_RESOURCE_NAME: ${{ secrets.QUARKUS_LANGCHAIN4J_AZURE_OPENAI_RESOURCE_NAME }}
        QUARKUS_LANGCHAIN4J_AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.QUARKUS_LANGCHAIN4J_AZURE_OPENAI_DEPLOYMENT_NAME }}
        QUARKUS_LANGCHAIN4J_AZURE_OPENAI_API_KEY: ${{ secrets.QUARKUS_LANGCHAIN4J_AZURE_OPENAI_API_KEY }}
        NEWSCAST_LOCATIONS_FFMPEG: ffmpeg
        CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY || 'localhost:5000' }}

    - name: Push container images
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      run: |
        export GIT_HASH=$(git rev-parse --short HEAD)
        cd content-api && quarkus image push -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
        cd ../reader-api && quarkus image push -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
        cd ../podcast-api && quarkus image push -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
      env:
        CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY || 'localhost:5000' }}

