name: Continuous integration

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'content-api/**'
      - 'podcast-api/**'
      - 'reader-api/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'content-api/**'
      - 'podcast-api/**'
      - 'reader-api/**'
      - '.github/workflows/ci.yml'
permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1

    - name: Run Maven build
      run: |
        export GIT_HASH=$(git rev-parse --short HEAD)
        ./mvnw clean verify -Dquarkus.test.profile=test -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
      env:
        TESTCONTAINERS_RYUK_DISABLED: true
        QUARKUS_LANGCHAIN4J_AZURE_OPENAI_RESOURCE_NAME: ${{ secrets.QUARKUS_LANGCHAIN4J_AZURE_OPENAI_RESOURCE_NAME }}
        QUARKUS_LANGCHAIN4J_AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.QUARKUS_LANGCHAIN4J_AZURE_OPENAI_DEPLOYMENT_NAME }}
        QUARKUS_LANGCHAIN4J_AZURE_OPENAI_API_KEY: ${{ secrets.QUARKUS_LANGCHAIN4J_AZURE_OPENAI_API_KEY }}
        NEWSCAST_LOCATIONS_FFMPEG: ffmpeg
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY || 'localhost:5000' }}

    - name: Login to Azure
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      uses: azure/login@v2
      with:
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Push content-api container image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      working-directory: content-api
      run: |
        export GIT_HASH=$(git rev-parse --short HEAD)
        mvn quarkus:image-push -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
      env:
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY || 'localhost:5000' }}
    - name: Push reader-api container image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      working-directory: reader-api
      run: |
        export GIT_HASH=$(git rev-parse --short HEAD)
        mvn quarkus:image-push -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
      env:
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY || 'localhost:5000' }}
    - name: Push podcast-api container image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      working-directory: podcast-api
      run: |
        export GIT_HASH=$(git rev-parse --short HEAD)
        mvn quarkus:image-push -Dquarkus.container-image.tag=1.0.0-${GIT_HASH}
      env:
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY || 'localhost:5000' }}
