name: Podcasts CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/podcasts/**'
      - '.github/workflows/podcasts-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/podcasts/**'
      - '.github/workflows/podcasts-ci.yml'
jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-latest
        container: ghcr.io/astral-sh/uv:debian-slim
        permissions:
            contents: read
            pull-requests: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              name: Checkout sources

            - name: Build packages
              working-directory: apps/podcasts
              run: uv build --link-mode=copy --all

            - name: Synchronize packages
              working-directory: apps/podcasts
              run: uv sync --all-packages

            - name: Lint with ruff
              working-directory: apps/podcasts
              run: uv run ruff check .

            # - name: Run tests
            #   working-directory: apps/podcasts
            #   run: uv run pytest --cov=agenttalks --cov-report xml:coverage.xml
            #   env:
            #     APP_DATABASE_URL: "NOT_SET"

            # - name: Report coverage
            #   uses: orgoro/coverage@v3.2
            #   with:
            #     coverageFile: apps/podcasts/coverage.xml
            #     token: ${{ secrets.GITHUB_TOKEN }}