name: Reader API CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'reader-api/**'
      - '.github/workflows/reader-api-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'reader-api/**'
      - '.github/workflows/reader-api-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and test reader-api with coverage
      working-directory: reader-api
      run: ./mvnw clean verify -Dquarkus.test.profile=test
      env:
        TESTCONTAINERS_RYUK_DISABLED: true
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./reader-api/target/jacoco-report/jacoco.xml
        flags: reader-api
        name: reader-api-coverage
        fail_ci_if_error: false