name: TextExtraction CI

on:
  push:
    branches:
      - main
    paths:
      - 'libs/textextraction/**'
      - '.github/workflows/textextraction-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'libs/textextraction/**'
      - '.github/workflows/textextraction-ci.yml'
jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-latest
        container: ghcr.io/astral-sh/uv:debian-slim
        permissions:
            contents: read
            pull-requests: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              name: Checkout sources

            - name: Build packages
              working-directory: libs/textextraction
              run: uv build --link-mode=copy --all

            - name: Synchronize packages
              working-directory: libs/textextraction
              run: uv sync --all-packages

            - name: Lint with ruff
              working-directory: libs/textextraction
              run: uv run ruff check .

            - name: Run tests
              working-directory: libs/textextraction
              run: uv run pytest --cov=reforge --cov-report xml:coverage.xml

            - name: Report coverage
              uses: orgoro/coverage@v3.2
              with:
                coverageFile: libs/textextraction/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}